server:
  port: 8080
  server:
    servlet:
      contextPath: /api
  cache:
    type: redis
    redis:
      time-to-live: 6000
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/vodafone_travel_assistant?currentSchema=vodafone_travel_assistant
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
travel-app:
  external-endpoints:
    geocoding: http://api.openweathermap.org/geo/1.0/direct?limit=1&appid=2bd1d944f7db37c226a223b5a4e25441
    weather: https://api.openweathermap.org/data/2.5/weather?appid=2bd1d944f7db37c226a223b5a4e25441
    exchange-rate: http://api.exchangeratesapi.io/v1/latest?access_key=7bc26ea85605f5d04070959c55261575&format=1
    world-bank-api: http://api.worldbank.org/v2/countries
    world-bank-api-test-local: http://api.worldbank.org/v2/countries/MZ/indicators/NY.GDP.MKTP.CD?format=json
  jwt:
    key: travel-app
    expiration-time: 360000000
    secret: dm9kYWZvbmVpc1YzcnlDMDBMM2NmYTc2ZWYxNDkzN2MxYzBlYTUxOWY4ZmMwNTdhODBmY2QwNGE3NDIwZjhlOGJjZDBhNzU2N2MyNzJlMDA3Yg==
  rate-limit:
    max-requests: 100
    time-window: 5
springdoc:
  api-docs:
    path: /api-docs
